version: '2'
sql:
    - engine: 'mysql'
      name: 'kokomed-fin'
      queries: '../../internal/mysql/queries/*'
      schema: '../../internal/mysql/migrations/*'
      gen:
          go:
              package: 'generated'
              out: '../../internal/mysql/generated'
              emit_json_tags: true
              emit_interface: true
              emit_empty_slices: true
              overrides:
                  - db_type: 'timestamptz'
                    go_type: 'time.Time'
                  - db_type: 'int'
                    go_type: 'uint32'
                  - db_type: 'decimal'
                    go_type: 'float64'
